/**
 * Style preference definitions — single source of truth for the wizard and settings panel.
 * Each entry describes one configurable style rule: its UI, default, and how it affects scanning.
 */

export type PreferenceCategory = "universal" | "academic" | "legal" | "fiction" | "marketing" | "business" | "strictness" | "punctuation" | "numbers" | "capitalisation" | "formatting";

export interface PreferenceDefinition {
  key: string;
  label: string;
  description: string;
  category: PreferenceCategory;
  inputType: "select" | "boolean" | "number" | "text";
  options?: { value: string; label: string }[];
  defaultValue: string | boolean | number;
  /** Which document types this preference applies to. ["all"] means always visible. */
  documentTypes: string[];
  /** If true, this setting is hidden behind "Advanced options" toggle. */
  advanced?: boolean;
  /** If set, this preference appears in the wizard at the given step. */
  wizardStep?: number;
  wizardPriority?: number;
  scanEffect?: {
    type: "prompt_token" | "library_toggle" | "threshold";
    /** For prompt_token: the [BRACKET] key injected into prompts. */
    tokenKey?: string;
    /** For library_toggle/threshold: which semantic pattern or library category. */
    ruleId?: string;
  };
}

export const PREFERENCE_CATEGORIES: { key: PreferenceCategory; label: string; documentTypes: string[] }[] = [
  { key: "universal", label: "Universal Preferences", documentTypes: ["all"] },
  { key: "academic", label: "Academic Settings", documentTypes: ["academic"] },
  { key: "legal", label: "Legal & Professional Settings", documentTypes: ["legal", "professional"] },
  { key: "fiction", label: "Fiction Settings", documentTypes: ["casual"] },
  { key: "marketing", label: "Marketing & Copywriting", documentTypes: ["professional", "casual"] },
  { key: "business", label: "Business Communication", documentTypes: ["professional"] },
  { key: "punctuation", label: "Punctuation & Typography", documentTypes: ["all"] },
  { key: "numbers", label: "Numbers & Dates", documentTypes: ["all"] },
  { key: "capitalisation", label: "Capitalisation & Lists", documentTypes: ["all"] },
  { key: "formatting", label: "Page Formatting", documentTypes: ["all"] },
  { key: "strictness", label: "Strictness & Voice", documentTypes: ["all"] },
];

export const PREFERENCE_DEFINITIONS: PreferenceDefinition[] = [
  // ── Universal ──────────────────────────────────────────────────────────────
  // Wizard page 1: Language & conventions (up to 8 items)
  {
    key: "english_variant",
    label: "English variant",
    description: "Which regional English conventions should your writing follow?",
    category: "universal",
    inputType: "select",
    options: [
      { value: "american", label: "American English" },
      { value: "british", label: "British English" },
      { value: "australian", label: "Australian English" },
      { value: "canadian", label: "Canadian English" },
      { value: "irish", label: "Irish English" },
      { value: "south_african", label: "South African English" },
    ],
    defaultValue: "american",
    documentTypes: ["all"],
    wizardStep: 1,
    wizardPriority: 1,
    scanEffect: { type: "prompt_token", tokenKey: "SPELLING_VARIANT" },
  },
  {
    key: "formality_level",
    label: "Formality level",
    description: "The expected level of formality in the writing.",
    category: "universal",
    inputType: "select",
    options: [
      { value: "very_formal", label: "Very formal" },
      { value: "formal", label: "Formal" },
      { value: "moderate", label: "Moderate" },
      { value: "casual", label: "Casual" },
    ],
    defaultValue: "formal",
    documentTypes: ["all"],
    wizardStep: 1,
    wizardPriority: 2,
    scanEffect: { type: "prompt_token", tokenKey: "FORMALITY_LEVEL" },
  },
  {
    key: "contractions_allowed",
    label: "Allow contractions",
    description: "Are contractions like \"don't\" and \"it's\" acceptable?",
    category: "universal",
    inputType: "boolean",
    defaultValue: true,
    documentTypes: ["all"],
    wizardStep: 1,
    wizardPriority: 3,
    scanEffect: { type: "threshold", ruleId: "missing_contractions" },
  },
  {
    key: "oxford_comma",
    label: "Oxford comma",
    description: "Use a comma before \"and\" in lists of three or more items?",
    category: "universal",
    inputType: "boolean",
    defaultValue: true,
    documentTypes: ["all"],
    wizardStep: 1,
    wizardPriority: 4,
    scanEffect: { type: "prompt_token", tokenKey: "OXFORD_COMMA" },
  },
  {
    key: "passive_voice_tolerance",
    label: "Passive voice tolerance",
    description: "How strictly should passive voice be flagged?",
    category: "universal",
    inputType: "select",
    options: [
      { value: "strict", label: "Strict \u2014 flag most passive voice" },
      { value: "moderate", label: "Moderate \u2014 flag excessive use" },
      { value: "relaxed", label: "Relaxed \u2014 only flag when unclear" },
    ],
    defaultValue: "moderate",
    documentTypes: ["all"],
    wizardStep: 1,
    wizardPriority: 5,
    scanEffect: { type: "prompt_token", tokenKey: "PASSIVE_VOICE_POLICY" },
  },
  {
    key: "quotation_style",
    label: "Quotation marks",
    description: "Double quotes (American convention) or single quotes (British convention)?",
    category: "universal",
    inputType: "select",
    options: [
      { value: "double", label: "Double quotes (\u201c \u201d)" },
      { value: "single", label: "Single quotes (\u2018 \u2019)" },
    ],
    defaultValue: "double",
    documentTypes: ["all"],
    wizardStep: 1,
    wizardPriority: 6,
    scanEffect: { type: "prompt_token", tokenKey: "QUOTATION_STYLE" },
  },
  {
    key: "punctuation_in_quotes",
    label: "Punctuation inside quotes",
    description: "Do periods and commas go inside or outside quotation marks?",
    category: "universal",
    inputType: "select",
    options: [
      { value: "inside", label: "Inside (American)" },
      { value: "outside", label: "Outside (British)" },
    ],
    defaultValue: "inside",
    documentTypes: ["all"],
    wizardStep: 1,
    wizardPriority: 7,
    scanEffect: { type: "prompt_token", tokenKey: "PUNCTUATION_IN_QUOTES" },
  },
  {
    key: "spaces_after_period",
    label: "Spaces after a period",
    description: "One space (modern standard) or two spaces (traditional) after a full stop?",
    category: "universal",
    inputType: "select",
    options: [
      { value: "one", label: "One space" },
      { value: "two", label: "Two spaces" },
    ],
    defaultValue: "one",
    documentTypes: ["all"],
    wizardStep: 1,
    wizardPriority: 8,
    scanEffect: { type: "prompt_token", tokenKey: "SPACES_AFTER_PERIOD" },
  },
  // Universal settings-only items
  {
    key: "acronyms_define_first_use",
    label: "Define acronyms on first use",
    description: "Should acronyms be written in full on first use, e.g. \"Chief Executive Officer (CEO)\"?",
    category: "universal",
    inputType: "boolean",
    defaultValue: true,
    documentTypes: ["all"],
    scanEffect: { type: "prompt_token", tokenKey: "ACRONYMS_POLICY" },
  },
  {
    key: "gender_neutral_language",
    label: "Gender-neutral language",
    description: "Flag non-inclusive or gendered language (e.g. \"chairman\" \u2192 \"chairperson\")?",
    category: "universal",
    inputType: "boolean",
    defaultValue: false,
    documentTypes: ["all"],
    scanEffect: { type: "prompt_token", tokenKey: "GENDER_NEUTRAL" },
  },
  {
    key: "sentence_length_flag",
    label: "Maximum sentence length (words)",
    description: "Flag sentences longer than this word count (0 = off).",
    category: "universal",
    inputType: "number",
    defaultValue: 0,
    documentTypes: ["all"],
    scanEffect: { type: "prompt_token", tokenKey: "SENTENCE_LENGTH_FLAG" },
  },

  // ── Academic ───────────────────────────────────────────────────────────────
  // Wizard page 2: Academic formatting (up to 8 items)
  {
    key: "citation_format",
    label: "Citation format",
    description: "The citation style your institution requires.",
    category: "academic",
    inputType: "select",
    options: [
      { value: "harvard", label: "Harvard" },
      { value: "apa", label: "APA (7th edition)" },
      { value: "mla", label: "MLA (9th edition)" },
      { value: "chicago", label: "Chicago / Turabian" },
      { value: "oxford", label: "Oxford" },
      { value: "bluebook", label: "Bluebook" },
      { value: "oscola", label: "OSCOLA" },
      { value: "vancouver", label: "Vancouver" },
      { value: "ieee", label: "IEEE" },
    ],
    defaultValue: "harvard",
    documentTypes: ["academic"],
    wizardStep: 2,
    wizardPriority: 1,
    scanEffect: { type: "prompt_token", tokenKey: "CITATION_FORMAT" },
  },
  {
    key: "citation_placement",
    label: "Citation placement",
    description: "Where do citations appear in your document?",
    category: "academic",
    inputType: "select",
    options: [
      { value: "inline", label: "Inline (in-text)" },
      { value: "footnotes", label: "Footnotes (bottom of page)" },
      { value: "endnotes", label: "Endnotes (end of document)" },
    ],
    defaultValue: "inline",
    documentTypes: ["academic"],
    wizardStep: 2,
    wizardPriority: 2,
    scanEffect: { type: "prompt_token", tokenKey: "CITATION_PLACEMENT" },
  },
  {
    key: "first_person_allowed",
    label: "First person allowed",
    description: "Is first person (\"I\", \"we\") acceptable?",
    category: "academic",
    inputType: "boolean",
    defaultValue: false,
    documentTypes: ["academic"],
    wizardStep: 2,
    wizardPriority: 3,
    scanEffect: { type: "prompt_token", tokenKey: "FIRST_PERSON_POLICY" },
  },
  {
    key: "paragraph_indent",
    label: "Paragraph indentation",
    description: "Should each paragraph's first line be indented?",
    category: "academic",
    inputType: "boolean",
    defaultValue: false,
    documentTypes: ["academic"],
    wizardStep: 2,
    wizardPriority: 4,
    scanEffect: { type: "prompt_token", tokenKey: "PARAGRAPH_INDENT" },
  },
  {
    key: "line_spacing",
    label: "Line spacing",
    description: "What line spacing does your institution require?",
    category: "academic",
    inputType: "select",
    options: [
      { value: "single", label: "Single" },
      { value: "1.5", label: "1.5 spacing" },
      { value: "double", label: "Double" },
    ],
    defaultValue: "double",
    documentTypes: ["academic"],
    wizardStep: 2,
    wizardPriority: 5,
    scanEffect: { type: "prompt_token", tokenKey: "LINE_SPACING" },
  },
  {
    key: "heading_style",
    label: "Heading format",
    description: "How should section headings be formatted?",
    category: "academic",
    inputType: "select",
    options: [
      { value: "numbered", label: "Numbered (1., 1.1, 1.1.1)" },
      { value: "unnumbered", label: "Unnumbered" },
      { value: "both", label: "Numbered and titled" },
    ],
    defaultValue: "unnumbered",
    documentTypes: ["academic"],
    wizardStep: 2,
    wizardPriority: 6,
  },
  {
    key: "bibliography_required",
    label: "Bibliography / reference list",
    description: "Must the document end with a bibliography or reference list?",
    category: "academic",
    inputType: "boolean",
    defaultValue: true,
    documentTypes: ["academic"],
    wizardStep: 2,
    wizardPriority: 7,
  },
  {
    key: "word_count_limit",
    label: "Word count limit",
    description: "Maximum word count (0 = no limit).",
    category: "academic",
    inputType: "number",
    defaultValue: 0,
    documentTypes: ["academic"],
    wizardStep: 2,
    wizardPriority: 8,
  },
  // Settings-only academic items (not in wizard to keep page 2 at 8)
  {
    key: "title_page_required",
    label: "Title/cover page required",
    description: "Whether the document must include a title or cover page.",
    category: "academic",
    inputType: "boolean",
    defaultValue: true,
    documentTypes: ["academic"],
  },
  {
    key: "abstract_required",
    label: "Abstract required",
    description: "Whether the document must include an abstract section.",
    category: "academic",
    inputType: "boolean",
    defaultValue: false,
    documentTypes: ["academic"],
  },
  {
    key: "block_quote_threshold",
    label: "Block quote threshold (words)",
    description: "Quotes longer than this many words should be formatted as block quotes.",
    category: "academic",
    inputType: "number",
    defaultValue: 40,
    documentTypes: ["academic"],
    scanEffect: { type: "prompt_token", tokenKey: "BLOCK_QUOTE_THRESHOLD" },
  },
  {
    key: "running_header",
    label: "Running header",
    description: "Does the document require a running header (shortened title at top of each page)?",
    category: "academic",
    inputType: "boolean",
    defaultValue: false,
    documentTypes: ["academic"],
  },
  {
    key: "table_figure_numbering",
    label: "Table and figure captions",
    description: "Where should table/figure numbers and captions appear?",
    category: "academic",
    inputType: "select",
    options: [
      { value: "above", label: "Above the table/figure" },
      { value: "below", label: "Below the table/figure" },
      { value: "none", label: "No numbering required" },
    ],
    defaultValue: "above",
    documentTypes: ["academic"],
  },
  {
    key: "appendices_format",
    label: "Appendices format",
    description: "How should appendices be labelled?",
    category: "academic",
    inputType: "select",
    options: [
      { value: "lettered", label: "Lettered (Appendix A, B, C)" },
      { value: "numbered", label: "Numbered (Appendix 1, 2, 3)" },
      { value: "none", label: "No appendices expected" },
    ],
    defaultValue: "lettered",
    documentTypes: ["academic"],
  },

  // ── Legal & Professional ───────────────────────────────────────────────────
  {
    key: "legal_citation_style",
    label: "Legal citation style",
    description: "The citation convention used in legal documents.",
    category: "legal",
    inputType: "select",
    options: [
      { value: "bluebook", label: "Bluebook" },
      { value: "oscola", label: "OSCOLA" },
      { value: "aglc", label: "AGLC (Australian)" },
      { value: "mcgill", label: "McGill (Canadian)" },
      { value: "none", label: "No specific style" },
    ],
    defaultValue: "none",
    documentTypes: ["legal"],
    wizardStep: 2,
    wizardPriority: 1,
    scanEffect: { type: "prompt_token", tokenKey: "LEGAL_CITATION_STYLE" },
  },
  {
    key: "defined_terms_caps",
    label: "Capitalise defined terms",
    description: "Whether defined terms should be capitalised throughout (e.g. \"the Agreement\", \"the Parties\").",
    category: "legal",
    inputType: "boolean",
    defaultValue: true,
    documentTypes: ["legal"],
    wizardStep: 2,
    wizardPriority: 2,
    scanEffect: { type: "prompt_token", tokenKey: "DEFINED_TERMS_CAPS" },
  },
  {
    key: "shall_vs_must",
    label: "\"Shall\" vs \"must\"",
    description: "Whether to prefer \"shall\" (traditional) or \"must\" (plain language) for obligations.",
    category: "legal",
    inputType: "select",
    options: [
      { value: "shall", label: "Use \"shall\"" },
      { value: "must", label: "Use \"must\" (plain language)" },
      { value: "either", label: "Either is acceptable" },
    ],
    defaultValue: "either",
    documentTypes: ["legal"],
    wizardStep: 2,
    wizardPriority: 3,
    scanEffect: { type: "prompt_token", tokenKey: "SHALL_VS_MUST" },
  },
  {
    key: "numbered_clauses",
    label: "Numbered clauses",
    description: "Whether clauses and sub-clauses should be numbered (e.g. 1.1, 1.1.1).",
    category: "legal",
    inputType: "boolean",
    defaultValue: true,
    documentTypes: ["legal"],
  },
  {
    key: "professional_tone",
    label: "Professional tone",
    description: "The expected tone for professional documents.",
    category: "legal",
    inputType: "select",
    options: [
      { value: "authoritative", label: "Authoritative and direct" },
      { value: "collaborative", label: "Collaborative and approachable" },
      { value: "neutral", label: "Neutral and objective" },
    ],
    defaultValue: "neutral",
    documentTypes: ["professional"],
    wizardStep: 2,
    wizardPriority: 4,
    scanEffect: { type: "prompt_token", tokenKey: "PROFESSIONAL_TONE" },
  },

  // ── Fiction ─────────────────────────────────────────────────────────────────
  {
    key: "narrative_pov",
    label: "Narrative point of view",
    description: "The perspective used in the writing.",
    category: "fiction",
    inputType: "select",
    options: [
      { value: "first", label: "First person" },
      { value: "second", label: "Second person" },
      { value: "third_limited", label: "Third person limited" },
      { value: "third_omniscient", label: "Third person omniscient" },
      { value: "mixed", label: "Mixed / varies" },
    ],
    defaultValue: "third_limited",
    documentTypes: ["casual"],
    scanEffect: { type: "prompt_token", tokenKey: "NARRATIVE_POV" },
  },
  {
    key: "dialogue_style",
    label: "Dialogue punctuation",
    description: "How dialogue is punctuated in the text.",
    category: "fiction",
    inputType: "select",
    options: [
      { value: "double_quotes", label: "Double quotes (American)" },
      { value: "single_quotes", label: "Single quotes (British)" },
      { value: "em_dashes", label: "Em dashes (Continental)" },
      { value: "none", label: "No dialogue" },
    ],
    defaultValue: "double_quotes",
    documentTypes: ["casual"],
    scanEffect: { type: "prompt_token", tokenKey: "DIALOGUE_STYLE" },
  },
  {
    key: "tense_consistency",
    label: "Tense consistency",
    description: "Whether to flag tense shifts within scenes or sections.",
    category: "fiction",
    inputType: "boolean",
    defaultValue: true,
    documentTypes: ["casual"],
    scanEffect: { type: "prompt_token", tokenKey: "TENSE_CONSISTENCY" },
  },
  {
    key: "show_dont_tell",
    label: "Flag \"telling\" language",
    description: "Flag instances of telling (e.g. \"she felt sad\") that could be shown through action.",
    category: "fiction",
    inputType: "boolean",
    defaultValue: false,
    documentTypes: ["casual"],
    scanEffect: { type: "prompt_token", tokenKey: "SHOW_DONT_TELL" },
  },

  // ── Marketing & Copywriting ────────────────────────────────────────────────
  {
    key: "brand_voice",
    label: "Brand voice",
    description: "The tone and personality of the brand.",
    category: "marketing",
    inputType: "select",
    options: [
      { value: "playful", label: "Playful and fun" },
      { value: "professional", label: "Professional and trustworthy" },
      { value: "bold", label: "Bold and provocative" },
      { value: "empathetic", label: "Warm and empathetic" },
      { value: "authoritative", label: "Expert and authoritative" },
    ],
    defaultValue: "professional",
    documentTypes: ["professional", "casual"],
    scanEffect: { type: "prompt_token", tokenKey: "BRAND_VOICE" },
  },
  {
    key: "cta_style",
    label: "Call-to-action style",
    description: "How direct calls to action should be.",
    category: "marketing",
    inputType: "select",
    options: [
      { value: "direct", label: "Direct (\"Buy now\", \"Sign up\")" },
      { value: "soft", label: "Soft (\"Learn more\", \"Explore\")" },
      { value: "conversational", label: "Conversational (\"Ready to start?\")" },
    ],
    defaultValue: "direct",
    documentTypes: ["professional", "casual"],
    scanEffect: { type: "prompt_token", tokenKey: "CTA_STYLE" },
  },
  {
    key: "jargon_tolerance",
    label: "Industry jargon tolerance",
    description: "Whether technical or industry jargon is acceptable.",
    category: "marketing",
    inputType: "select",
    options: [
      { value: "avoid", label: "Avoid \u2014 use plain language" },
      { value: "moderate", label: "Some jargon OK for expert audiences" },
      { value: "welcome", label: "Jargon expected (B2B / technical)" },
    ],
    defaultValue: "avoid",
    documentTypes: ["professional", "casual"],
    scanEffect: { type: "prompt_token", tokenKey: "JARGON_TOLERANCE" },
  },

  // ── Business Communication ─────────────────────────────────────────────────
  {
    key: "email_formality",
    label: "Email formality",
    description: "The expected level of formality in business emails and memos.",
    category: "business",
    inputType: "select",
    options: [
      { value: "formal", label: "Formal (\"Dear Mr. Smith\")" },
      { value: "semi_formal", label: "Semi-formal (\"Hi John\")" },
      { value: "informal", label: "Informal (\"Hey team\")" },
    ],
    defaultValue: "semi_formal",
    documentTypes: ["professional"],
    scanEffect: { type: "prompt_token", tokenKey: "EMAIL_FORMALITY" },
  },
  {
    key: "bullet_points_preferred",
    label: "Prefer bullet points",
    description: "Whether to favour bullet points over long paragraphs for clarity.",
    category: "business",
    inputType: "boolean",
    defaultValue: true,
    documentTypes: ["professional"],
    scanEffect: { type: "prompt_token", tokenKey: "BULLET_POINTS" },
  },
  {
    key: "executive_summary",
    label: "Executive summary expected",
    description: "Whether longer documents should include an executive summary at the top.",
    category: "business",
    inputType: "boolean",
    defaultValue: false,
    documentTypes: ["professional"],
  },
  {
    key: "action_items_format",
    label: "Action items format",
    description: "How action items and next steps should be formatted.",
    category: "business",
    inputType: "select",
    options: [
      { value: "inline", label: "Inline in text" },
      { value: "bulleted", label: "Separate bulleted list" },
      { value: "table", label: "Table (owner, deadline, action)" },
    ],
    defaultValue: "bulleted",
    documentTypes: ["professional"],
  },

  // ── Punctuation & Typography ────────────────────────────────────────────────
  {
    key: "em_dash_style",
    label: "Em dash style",
    description: "How should em dashes be formatted?",
    category: "punctuation",
    inputType: "select",
    options: [
      { value: "no_spaces", label: "No spaces\u2014like this" },
      { value: "spaced", label: "Spaced \u2014 like this" },
      { value: "en_dash", label: "Use en dash \u2013 instead" },
    ],
    defaultValue: "no_spaces",
    documentTypes: ["all"],
    scanEffect: { type: "prompt_token", tokenKey: "EM_DASH_STYLE" },
  },
  {
    key: "ellipsis_style",
    label: "Ellipsis style",
    description: "How should ellipses be written?",
    category: "punctuation",
    inputType: "select",
    options: [
      { value: "unicode", label: "Single character (\u2026)" },
      { value: "three_dots", label: "Three periods (...)" },
      { value: "spaced", label: "Spaced periods (. . .)" },
    ],
    defaultValue: "three_dots",
    documentTypes: ["all"],
    scanEffect: { type: "prompt_token", tokenKey: "ELLIPSIS_STYLE" },
  },
  {
    key: "apostrophe_decades",
    label: "Decades and plurals",
    description: "How should decades be written?",
    category: "punctuation",
    inputType: "select",
    options: [
      { value: "no_apostrophe", label: "1990s (no apostrophe)" },
      { value: "apostrophe", label: "1990's (with apostrophe)" },
    ],
    defaultValue: "no_apostrophe",
    documentTypes: ["all"],
    scanEffect: { type: "prompt_token", tokenKey: "APOSTROPHE_DECADES" },
  },

  // ── Numbers & Dates ────────────────────────────────────────────────────────
  {
    key: "number_spell_threshold",
    label: "Spell out numbers below",
    description: "Spell out numbers below this value (e.g. 10 means write \"nine\" but \"10\").",
    category: "numbers",
    inputType: "number",
    defaultValue: 10,
    documentTypes: ["all"],
    scanEffect: { type: "prompt_token", tokenKey: "NUMBER_SPELL_THRESHOLD" },
  },
  {
    key: "number_start_sentence",
    label: "Spell out numbers at start of sentence",
    description: "Always write numbers as words when they begin a sentence?",
    category: "numbers",
    inputType: "boolean",
    defaultValue: true,
    documentTypes: ["all"],
    scanEffect: { type: "prompt_token", tokenKey: "NUMBER_START_SENTENCE" },
  },
  {
    key: "date_format",
    label: "Date format",
    description: "How should dates be written?",
    category: "numbers",
    inputType: "select",
    options: [
      { value: "dd_mm_yyyy", label: "DD/MM/YYYY (British)" },
      { value: "mm_dd_yyyy", label: "MM/DD/YYYY (American)" },
      { value: "d_month_yyyy", label: "1 January 2025" },
      { value: "month_d_yyyy", label: "January 1, 2025" },
      { value: "yyyy_mm_dd", label: "2025-01-01 (ISO)" },
    ],
    defaultValue: "month_d_yyyy",
    documentTypes: ["all"],
    scanEffect: { type: "prompt_token", tokenKey: "DATE_FORMAT" },
  },
  {
    key: "time_format",
    label: "Time format",
    description: "12-hour or 24-hour clock?",
    category: "numbers",
    inputType: "select",
    options: [
      { value: "12_hour", label: "12-hour (2:30 PM)" },
      { value: "24_hour", label: "24-hour (14:30)" },
    ],
    defaultValue: "12_hour",
    documentTypes: ["all"],
    scanEffect: { type: "prompt_token", tokenKey: "TIME_FORMAT" },
  },
  {
    key: "percentage_format",
    label: "Percentage format",
    description: "Use the word \"percent\" or the symbol \"%\"?",
    category: "numbers",
    inputType: "select",
    options: [
      { value: "symbol", label: "Symbol (25%)" },
      { value: "word", label: "Word (25 percent)" },
    ],
    defaultValue: "symbol",
    documentTypes: ["all"],
    scanEffect: { type: "prompt_token", tokenKey: "PERCENTAGE_FORMAT" },
  },

  // ── Capitalisation & Lists ─────────────────────────────────────────────────
  {
    key: "heading_capitalisation",
    label: "Heading capitalisation",
    description: "How should headings and titles be capitalised?",
    category: "capitalisation",
    inputType: "select",
    options: [
      { value: "title_case", label: "Title Case (Capitalise Major Words)" },
      { value: "sentence_case", label: "Sentence case (Only first word)" },
    ],
    defaultValue: "title_case",
    documentTypes: ["all"],
    scanEffect: { type: "prompt_token", tokenKey: "HEADING_CAPITALISATION" },
  },
  {
    key: "capitalise_after_colon",
    label: "Capitalise after colon",
    description: "Should the first word after a colon be capitalised?",
    category: "capitalisation",
    inputType: "boolean",
    defaultValue: false,
    documentTypes: ["all"],
    scanEffect: { type: "prompt_token", tokenKey: "CAPITALISE_AFTER_COLON" },
  },
  {
    key: "list_punctuation",
    label: "List punctuation",
    description: "How should list items end?",
    category: "capitalisation",
    inputType: "select",
    options: [
      { value: "full_stops", label: "Full stops (periods)" },
      { value: "semicolons", label: "Semicolons" },
      { value: "none", label: "No punctuation" },
    ],
    defaultValue: "none",
    documentTypes: ["all"],
    scanEffect: { type: "prompt_token", tokenKey: "LIST_PUNCTUATION" },
  },
  {
    key: "list_capitalise_first",
    label: "Capitalise list items",
    description: "Should the first word of each list item be capitalised?",
    category: "capitalisation",
    inputType: "boolean",
    defaultValue: true,
    documentTypes: ["all"],
    scanEffect: { type: "prompt_token", tokenKey: "LIST_CAPITALISE_FIRST" },
  },

  // ── Page Formatting ────────────────────────────────────────────────────────
  {
    key: "text_alignment",
    label: "Text alignment",
    description: "How should body text be aligned?",
    category: "formatting",
    inputType: "select",
    options: [
      { value: "left", label: "Left-aligned (ragged right)" },
      { value: "justified", label: "Justified (even margins)" },
    ],
    defaultValue: "left",
    documentTypes: ["all"],
    scanEffect: { type: "prompt_token", tokenKey: "TEXT_ALIGNMENT" },
  },
  {
    key: "font_preference",
    label: "Font family",
    description: "What type of font does the style guide require?",
    category: "formatting",
    inputType: "select",
    options: [
      { value: "serif", label: "Serif (Times New Roman)" },
      { value: "sans_serif", label: "Sans-serif (Calibri)" },
      { value: "no_preference", label: "No preference" },
    ],
    defaultValue: "no_preference",
    documentTypes: ["all"],
  },
  {
    key: "font_name",
    label: "Exact font name",
    description: "Specify the exact font your style guide requires (e.g. Helvetica, Garamond, Courier New).",
    category: "formatting",
    inputType: "text",
    defaultValue: "",
    documentTypes: ["all"],
    advanced: true,
  },
  {
    key: "font_size",
    label: "Font size",
    description: "What font size is required?",
    category: "formatting",
    inputType: "select",
    options: [
      { value: "10", label: "10pt" },
      { value: "11", label: "11pt" },
      { value: "12", label: "12pt" },
      { value: "no_preference", label: "No preference" },
    ],
    defaultValue: "12",
    documentTypes: ["all"],
  },
  {
    key: "font_size_exact",
    label: "Exact font size (pt)",
    description: "Specify an exact font size if not 10, 11, or 12 (e.g. 9, 13, 14).",
    category: "formatting",
    inputType: "number",
    defaultValue: "",
    documentTypes: ["all"],
    advanced: true,
  },
  {
    key: "margin_size",
    label: "Margins",
    description: "What margin size is required?",
    category: "formatting",
    inputType: "select",
    options: [
      { value: "1_inch", label: "1 inch / 2.54 cm (all sides)" },
      { value: "1.25_inch", label: "1.25 inch / 3.17 cm" },
      { value: "2.5_cm", label: "2.5 cm" },
      { value: "no_preference", label: "No preference" },
    ],
    defaultValue: "1_inch",
    documentTypes: ["all"],
  },
  {
    key: "margin_top_inches",
    label: "Top margin (inches)",
    description: "Exact top margin in inches (e.g. 0.5, 0.75, 1.5).",
    category: "formatting",
    inputType: "text",
    defaultValue: "",
    documentTypes: ["all"],
    advanced: true,
  },
  {
    key: "margin_bottom_inches",
    label: "Bottom margin (inches)",
    description: "Exact bottom margin in inches.",
    category: "formatting",
    inputType: "text",
    defaultValue: "",
    documentTypes: ["all"],
    advanced: true,
  },
  {
    key: "margin_left_inches",
    label: "Left margin (inches)",
    description: "Exact left margin in inches.",
    category: "formatting",
    inputType: "text",
    defaultValue: "",
    documentTypes: ["all"],
    advanced: true,
  },
  {
    key: "margin_right_inches",
    label: "Right margin (inches)",
    description: "Exact right margin in inches.",
    category: "formatting",
    inputType: "text",
    defaultValue: "",
    documentTypes: ["all"],
    advanced: true,
  },
  {
    key: "indent_size_inches",
    label: "Indent size (inches)",
    description: "How far to indent the first line of each paragraph (e.g. 0.5).",
    category: "formatting",
    inputType: "text",
    defaultValue: "0.5",
    documentTypes: ["all"],
    advanced: true,
  },
  {
    key: "page_numbering",
    label: "Page numbering",
    description: "Where should page numbers appear?",
    category: "formatting",
    inputType: "select",
    options: [
      { value: "top_right", label: "Top right" },
      { value: "bottom_center", label: "Bottom centre" },
      { value: "bottom_right", label: "Bottom right" },
      { value: "none", label: "No page numbers" },
    ],
    defaultValue: "bottom_center",
    documentTypes: ["all"],
  },
  {
    key: "header_text",
    label: "Running header text",
    description: "Text to show in the page header (e.g. your surname, short title). Leave blank for none.",
    category: "formatting",
    inputType: "text",
    defaultValue: "",
    documentTypes: ["all"],
    advanced: true,
  },

  // ── Strictness & Voice ─────────────────────────────────────────────────────
  {
    key: "scan_strictness",
    label: "Scan strictness",
    description: "How aggressively the scanner flags potential AI patterns. Stricter catches more but may flag natural writing.",
    category: "strictness",
    inputType: "select",
    options: [
      { value: "lenient", label: "Lenient \u2014 only flag strong AI signals" },
      { value: "balanced", label: "Balanced \u2014 flag likely AI patterns" },
      { value: "strict", label: "Strict \u2014 flag anything that could be AI" },
    ],
    defaultValue: "balanced",
    documentTypes: ["all"],
    scanEffect: { type: "prompt_token", tokenKey: "SCAN_STRICTNESS" },
  },
  {
    key: "preserve_voice",
    label: "Preserve writer's voice",
    description: "How much suggestions should preserve your original voice vs rewriting for naturalness.",
    category: "strictness",
    inputType: "select",
    options: [
      { value: "high", label: "High \u2014 minimal changes, keep my phrasing" },
      { value: "moderate", label: "Moderate \u2014 balance voice with naturalness" },
      { value: "low", label: "Low \u2014 prioritise natural-sounding rewrites" },
    ],
    defaultValue: "moderate",
    documentTypes: ["all"],
    scanEffect: { type: "prompt_token", tokenKey: "PRESERVE_VOICE" },
  },
  {
    key: "suggestion_creativity",
    label: "Suggestion creativity",
    description: "How creative or conservative the replacement suggestions should be.",
    category: "strictness",
    inputType: "select",
    options: [
      { value: "conservative", label: "Conservative \u2014 safe, close to original" },
      { value: "moderate", label: "Moderate \u2014 balanced variety" },
      { value: "creative", label: "Creative \u2014 more varied alternatives" },
    ],
    defaultValue: "moderate",
    documentTypes: ["all"],
    scanEffect: { type: "prompt_token", tokenKey: "SUGGESTION_CREATIVITY" },
  },
  {
    key: "target_audience_level",
    label: "Target reading level",
    description: "The expected reading level of the audience.",
    category: "strictness",
    inputType: "select",
    options: [
      { value: "general", label: "General public" },
      { value: "educated", label: "Educated adult" },
      { value: "expert", label: "Subject expert" },
      { value: "academic", label: "Academic / peer reviewer" },
    ],
    defaultValue: "educated",
    documentTypes: ["all"],
    scanEffect: { type: "prompt_token", tokenKey: "TARGET_READING_LEVEL" },
  },
];

/**
 * Returns preference definitions filtered for a given document type.
 */
export function getDefinitionsForDocType(documentType: string | null): PreferenceDefinition[] {
  if (!documentType) return PREFERENCE_DEFINITIONS.filter((d) => d.documentTypes.includes("all"));
  return PREFERENCE_DEFINITIONS.filter(
    (d) => d.documentTypes.includes("all") || d.documentTypes.includes(documentType),
  );
}

/**
 * Returns the default value map for a given document type.
 */
export function getDefaultPreferences(documentType: string | null): Record<string, string | boolean | number> {
  const defs = getDefinitionsForDocType(documentType);
  const defaults: Record<string, string | boolean | number> = {};
  for (const d of defs) defaults[d.key] = d.defaultValue;
  return defaults;
}
